# Generated by go2rpm
%bcond_without check

# https://github.com/fortytw2/leaktest
%global goipath         github.com/fortytw2/leaktest
Version:                1.3.0

%gometa

%global common_description %{expand:
Goroutine Leak Detector.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        13%{?dist}
Summary:        Goroutine Leak Detector

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}
# Increase timeout for s390x
Patch0:         increase-timeout.patch

%description
%{common_description}

%gopkg

%prep
%goprep
%patch -P0 -p1

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Mon May 13 2024 Martin Magr <mmagr@redhat.com> - 1.3.0-13
- Fedora import

